name: Linter & Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions flake8 codecov
        pip install -r requirements.dev.txt

    - name: "Test: Lint (flake8, black, isort)"
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count
        black . --check
        isort --check-only --diff setup.py durin example_project tests


    - name: "Test: tox tests"
      run: |
        # run tests with coverage
        tox

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
